/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChangePanel;
import java.awt.Color;

/**
 *
 * @author GILSON
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.btnHome.setSelected(true);
        new ChangePanel(pnlContainer, new frmHome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new rsbuttom.RSButtonMetro();
        btnPet = new rsbuttom.RSButtonMetro();
        btnOwner = new rsbuttom.RSButtonMetro();
        btnSettings = new rsbuttom.RSButtonMetro();
        pnlHome = new javax.swing.JPanel();
        pnlPet = new javax.swing.JPanel();
        pnlOwner = new javax.swing.JPanel();
        pnlSettings = new javax.swing.JPanel();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        pnlContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 153, 103));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VETERINARIA BOXER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(972, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));

        jPanel4.setBackground(new java.awt.Color(239, 238, 244));

        jLabel1.setBackground(new java.awt.Color(166, 166, 166));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("MENÚ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/home-run.png"))); // NOI18N
        btnHome.setText("INICIO");
        btnHome.setToolTipText("");
        btnHome.setColorHover(new java.awt.Color(204, 204, 204));
        btnHome.setColorNormal(new java.awt.Color(204, 204, 204));
        btnHome.setColorPressed(new java.awt.Color(204, 204, 204));
        btnHome.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnHome.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnHome.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setIconTextGap(25);
        btnHome.setPreferredSize(new java.awt.Dimension(180, 35));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPet.setBackground(new java.awt.Color(239, 238, 244));
        btnPet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/pet.png"))); // NOI18N
        btnPet.setText("MASCOTA");
        btnPet.setToolTipText("");
        btnPet.setColorHover(new java.awt.Color(204, 204, 204));
        btnPet.setColorNormal(new java.awt.Color(239, 238, 244));
        btnPet.setColorPressed(new java.awt.Color(204, 204, 204));
        btnPet.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnPet.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnPet.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnPet.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPet.setIconTextGap(25);
        btnPet.setPreferredSize(new java.awt.Dimension(180, 35));
        btnPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPetMousePressed(evt);
            }
        });
        btnPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetActionPerformed(evt);
            }
        });

        btnOwner.setBackground(new java.awt.Color(239, 238, 244));
        btnOwner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/user.png"))); // NOI18N
        btnOwner.setText("PROPIETARIO");
        btnOwner.setToolTipText("");
        btnOwner.setColorHover(new java.awt.Color(204, 204, 204));
        btnOwner.setColorNormal(new java.awt.Color(239, 238, 244));
        btnOwner.setColorPressed(new java.awt.Color(204, 204, 204));
        btnOwner.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnOwner.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnOwner.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnOwner.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnOwner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOwner.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnOwner.setIconTextGap(25);
        btnOwner.setPreferredSize(new java.awt.Dimension(180, 35));
        btnOwner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOwnerMousePressed(evt);
            }
        });
        btnOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOwnerActionPerformed(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(239, 238, 244));
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/gear.png"))); // NOI18N
        btnSettings.setText("AJUSTES");
        btnSettings.setToolTipText("");
        btnSettings.setColorHover(new java.awt.Color(204, 204, 204));
        btnSettings.setColorNormal(new java.awt.Color(239, 238, 244));
        btnSettings.setColorPressed(new java.awt.Color(204, 204, 204));
        btnSettings.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnSettings.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnSettings.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnSettings.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSettings.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSettings.setIconTextGap(25);
        btnSettings.setPreferredSize(new java.awt.Dimension(180, 35));
        btnSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSettingsMousePressed(evt);
            }
        });
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        pnlHome.setBackground(new java.awt.Color(51, 153, 103));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlPet.setBackground(new java.awt.Color(239, 238, 244));

        javax.swing.GroupLayout pnlPetLayout = new javax.swing.GroupLayout(pnlPet);
        pnlPet.setLayout(pnlPetLayout);
        pnlPetLayout.setHorizontalGroup(
            pnlPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlPetLayout.setVerticalGroup(
            pnlPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlOwner.setBackground(new java.awt.Color(239, 238, 244));

        javax.swing.GroupLayout pnlOwnerLayout = new javax.swing.GroupLayout(pnlOwner);
        pnlOwner.setLayout(pnlOwnerLayout);
        pnlOwnerLayout.setHorizontalGroup(
            pnlOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlOwnerLayout.setVerticalGroup(
            pnlOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnlSettings.setBackground(new java.awt.Color(239, 238, 244));

        javax.swing.GroupLayout pnlSettingsLayout = new javax.swing.GroupLayout(pnlSettings);
        pnlSettings.setLayout(pnlSettingsLayout);
        pnlSettingsLayout.setHorizontalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlSettingsLayout.setVerticalGroup(
            pnlSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(pnlPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnPet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(pnlOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(pnlSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(298, 298, 298))
        );

        pnlContainer.setBackground(new java.awt.Color(239, 238, 244));
        pnlContainer.setPreferredSize(new java.awt.Dimension(1540, 710));
        pnlContainer.setLayout(new javax.swing.BoxLayout(pnlContainer, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 708, Short.MAX_VALUE)
                    .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        new ChangePanel(pnlContainer, new frmHome());

        if (this.btnHome.isSelected()) {
            //cambiar de color el indicador (panel de la izquierda)
            this.pnlHome.setBackground(new Color(51, 153, 103));//color verde
            this.btnHome.setColorNormal(new Color(204, 204, 204));
            this.btnHome.setColorHover(new Color(204, 204, 204));
            this.btnHome.setColorPressed(new Color(204, 204, 204));

            this.pnlPet.setBackground(new Color(239, 238, 244));
            this.btnPet.setColorNormal(new Color(239, 238, 244));
            this.btnPet.setColorHover(new Color(204, 204, 204));
            this.btnPet.setColorPressed(new Color(204, 204, 204));

            this.pnlOwner.setBackground(new Color(239, 238, 244));
            this.btnOwner.setColorNormal(new Color(239, 238, 244));
            this.btnOwner.setColorHover(new Color(204, 204, 204));
            this.btnOwner.setColorPressed(new Color(204, 204, 204));

            this.pnlSettings.setBackground(new Color(239, 238, 244));
            this.btnSettings.setColorNormal(new Color(239, 238, 244));
            this.btnSettings.setColorHover(new Color(204, 204, 204));
            this.btnSettings.setColorPressed(new Color(204, 204, 204));

        } else {
            this.pnlHome.setBackground(new Color(239, 238, 244));
            this.btnHome.setColorNormal(new Color(239, 238, 244));
            this.btnHome.setColorHover(new Color(204, 204, 204));
            this.btnHome.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetActionPerformed
        new ChangePanel(pnlContainer, new frmPets());

        if (this.btnPet.isSelected()) {
            this.pnlPet.setBackground(new Color(51, 153, 103));//color verde
            this.btnPet.setColorNormal(new Color(204, 204, 204));
            this.btnPet.setColorHover(new Color(204, 204, 204));
            this.btnPet.setColorPressed(new Color(204, 204, 204));

            this.pnlHome.setBackground(new Color(239, 238, 244));
            this.btnHome.setColorNormal(new Color(239, 238, 244));
            this.btnHome.setColorHover(new Color(204, 204, 204));
            this.btnHome.setColorPressed(new Color(204, 204, 204));

            this.pnlOwner.setBackground(new Color(239, 238, 244));
            this.btnOwner.setColorNormal(new Color(239, 238, 244));
            this.btnOwner.setColorHover(new Color(204, 204, 204));
            this.btnOwner.setColorPressed(new Color(204, 204, 204));

            this.pnlSettings.setBackground(new Color(239, 238, 244));
            this.btnSettings.setColorNormal(new Color(239, 238, 244));
            this.btnSettings.setColorHover(new Color(204, 204, 204));
            this.btnSettings.setColorPressed(new Color(204, 204, 204));
        } else {
            this.pnlPet.setBackground(new Color(239, 238, 244));
            this.btnPet.setColorNormal(new Color(239, 238, 244));
            this.btnPet.setColorHover(new Color(204, 204, 204));
            this.btnPet.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnPetActionPerformed

    private void btnOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOwnerActionPerformed
        new ChangePanel(pnlContainer, new frmOwner());

        if (this.btnOwner.isSelected()) {
            this.pnlOwner.setBackground(new Color(51, 153, 103));//color verde
            this.btnOwner.setColorNormal(new Color(204, 204, 204));
            this.btnOwner.setColorHover(new Color(204, 204, 204));
            this.btnOwner.setColorPressed(new Color(204, 204, 204));

            this.pnlHome.setBackground(new Color(239, 238, 244));
            this.btnHome.setColorNormal(new Color(239, 238, 244));
            this.btnHome.setColorHover(new Color(204, 204, 204));
            this.btnHome.setColorPressed(new Color(204, 204, 204));

            this.pnlPet.setBackground(new Color(239, 238, 244));
            this.btnPet.setColorNormal(new Color(239, 238, 244));
            this.btnPet.setColorHover(new Color(204, 204, 204));
            this.btnPet.setColorPressed(new Color(204, 204, 204));

            this.pnlSettings.setBackground(new Color(239, 238, 244));
            this.btnSettings.setColorNormal(new Color(239, 238, 244));
            this.btnSettings.setColorHover(new Color(204, 204, 204));
            this.btnSettings.setColorPressed(new Color(204, 204, 204));
        } else {
            this.pnlOwner.setBackground(new Color(239, 238, 244));
            this.btnOwner.setColorNormal(new Color(239, 238, 244));
            this.btnOwner.setColorHover(new Color(204, 204, 204));
            this.btnOwner.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnOwnerActionPerformed

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        this.btnHome.setSelected(true);
        this.btnPet.setSelected(false);
        this.btnOwner.setSelected(false);
        this.btnSettings.setSelected(false);
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnPetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPetMousePressed
        this.btnHome.setSelected(false);
        this.btnPet.setSelected(true);
        this.btnOwner.setSelected(false);
        this.btnSettings.setSelected(false);
    }//GEN-LAST:event_btnPetMousePressed

    private void btnOwnerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOwnerMousePressed
        this.btnHome.setSelected(false);
        this.btnPet.setSelected(false);
        this.btnOwner.setSelected(true);
        this.btnSettings.setSelected(false);
    }//GEN-LAST:event_btnOwnerMousePressed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        new ChangePanel(pnlContainer, new frmSettings());
        if (this.btnSettings.isSelected()) {
            this.pnlSettings.setBackground(new Color(51, 153, 103));//color verde
            this.btnSettings.setColorNormal(new Color(204, 204, 204));
            this.btnSettings.setColorHover(new Color(204, 204, 204));
            this.btnSettings.setColorPressed(new Color(204, 204, 204));

            this.pnlHome.setBackground(new Color(239, 238, 244));
            this.btnHome.setColorNormal(new Color(239, 238, 244));
            this.btnHome.setColorHover(new Color(204, 204, 204));
            this.btnHome.setColorPressed(new Color(204, 204, 204));

            this.pnlPet.setBackground(new Color(239, 238, 244));
            this.btnPet.setColorNormal(new Color(239, 238, 244));
            this.btnPet.setColorHover(new Color(204, 204, 204));
            this.btnPet.setColorPressed(new Color(204, 204, 204));

            this.pnlOwner.setBackground(new Color(239, 238, 244));
            this.btnOwner.setColorNormal(new Color(239, 238, 244));
            this.btnOwner.setColorHover(new Color(204, 204, 204));
            this.btnOwner.setColorPressed(new Color(204, 204, 204));
        } else {
            this.pnlSettings.setBackground(new Color(239, 238, 244));
            this.btnSettings.setColorNormal(new Color(239, 238, 244));
            this.btnSettings.setColorHover(new Color(204, 204, 204));
            this.btnSettings.setColorPressed(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnSettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingsMousePressed
        this.btnHome.setSelected(false);
        this.btnPet.setSelected(false);
        this.btnOwner.setSelected(false);
        this.btnSettings.setSelected(true);
    }//GEN-LAST:event_btnSettingsMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnHome;
    private rsbuttom.RSButtonMetro btnOwner;
    private rsbuttom.RSButtonMetro btnPet;
    private rsbuttom.RSButtonMetro btnSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlOwner;
    private javax.swing.JPanel pnlPet;
    private javax.swing.JPanel pnlSettings;
    // End of variables declaration//GEN-END:variables
}
