/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChangePanel;
import java.awt.Color;

/**
 *
 * @author GILSON
 */
public class frmPetOfOwner extends javax.swing.JFrame {

    /**
     * Creates new form frmPeOfOwnser
     */
    int layoutX;
    int layoutY;
    boolean max = false;
    boolean switchPO = true;
    //cerrar ventanas hijas
    boolean switchHC = false;

    frmClinicHistory formHC = new frmClinicHistory();
    frmMedicalConsultation formMC = new frmMedicalConsultation();
    frmPets fromPet = new frmPets();

    public frmPetOfOwner() {
        initComponents();
    }

    private void openClinicHistory() {
        formHC.show();
        formHC.setLocationRelativeTo(this);
        switchHC = true;
    }

    private void openFrmPets(java.awt.event.MouseEvent evt) {
        new ChangePanel(frmPrincipal.pnlContainer, new frmPets());

        //cerrar ventanas hijas abiertas
        if (switchPO) {
            this.dispose();
            if (switchHC) {
                formHC.close(evt);
                switchHC = false;
            }
            switchPO = false;
        }

        customBtnFrmPrincipal();
    }

    private void customBtnFrmPrincipal() {
        frmPrincipal.btnHome.setSelected(false);
        frmPrincipal.btnPet.setSelected(true);
        frmPrincipal.btnOwner.setSelected(false);
        frmPrincipal.btnSettings.setSelected(false);

        if (frmPrincipal.btnPet.isSelected()) {
            frmPrincipal.pnlPet.setBackground(new Color(51, 153, 103));//color verde
            frmPrincipal.btnPet.setColorNormal(new Color(204, 204, 204));
            frmPrincipal.btnPet.setColorHover(new Color(204, 204, 204));
            frmPrincipal.btnPet.setColorPressed(new Color(204, 204, 204));

            frmPrincipal.pnlHome.setBackground(new Color(239, 238, 244));
            frmPrincipal.btnHome.setColorNormal(new Color(239, 238, 244));
            frmPrincipal.btnHome.setColorHover(new Color(204, 204, 204));
            frmPrincipal.btnHome.setColorPressed(new Color(204, 204, 204));

            frmPrincipal.pnlOwner.setBackground(new Color(239, 238, 244));
            frmPrincipal.btnOwner.setColorNormal(new Color(239, 238, 244));
            frmPrincipal.btnOwner.setColorHover(new Color(204, 204, 204));
            frmPrincipal.btnOwner.setColorPressed(new Color(204, 204, 204));

            frmPrincipal.pnlSettings.setBackground(new Color(239, 238, 244));
            frmPrincipal.btnSettings.setColorNormal(new Color(239, 238, 244));
            frmPrincipal.btnSettings.setColorHover(new Color(204, 204, 204));
            frmPrincipal.btnSettings.setColorPressed(new Color(204, 204, 204));
        } else {
            frmPrincipal.pnlPet.setBackground(new Color(239, 238, 244));
            frmPrincipal.btnPet.setColorNormal(new Color(239, 238, 244));
            frmPrincipal.btnPet.setColorHover(new Color(204, 204, 204));
            frmPrincipal.btnPet.setColorPressed(new Color(204, 204, 204));
        }
    }

    private void insertDetailOwner() {
        //bloquerar campos nombre direccion telefono
        frmPets.txtNameOwner.enable(false);
        frmPets.txtAdressOwner.enable(false);
        frmPets.txtPhoneOwner.enable(false);

        //llenar campos bloqueados
        frmPets.txtNameOwner.setText(lblNameOwnerDP.getText());
        frmPets.txtAdressOwner.setText(lblAddressOwnerDP.getText());
        frmPets.txtPhoneOwner.setText(lblPhoneOwnerDP.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCH = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new rojeru_san.RSButton();
        btnMin = new rojeru_san.RSButton();
        rSPanelRound1 = new rojeru_san.rspanel.RSPanelRound();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNameOwnerDP = new javax.swing.JLabel();
        lblPhoneOwnerDP = new javax.swing.JLabel();
        lblAddressOwnerDP = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnNewPetPO = new rojeru_san.RSButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rSTableMetro1 = new RSMaterialComponent.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlCH.setBackground(new java.awt.Color(51, 153, 51));
        pnlCH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlCHMouseDragged(evt);
            }
        });
        pnlCH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCHMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalle de Propietario");

        btnClose.setBackground(new java.awt.Color(51, 153, 51));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/close.png"))); // NOI18N
        btnClose.setColorHover(new java.awt.Color(244, 67, 54));
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.setIconTextGap(0);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(51, 153, 51));
        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/min.png"))); // NOI18N
        btnMin.setColorHover(new java.awt.Color(102, 102, 102));
        btnMin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMin.setIconTextGap(0);
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCHLayout = new javax.swing.GroupLayout(pnlCH);
        pnlCH.setLayout(pnlCHLayout);
        pnlCHLayout.setHorizontalGroup(
            pnlCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCHLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCHLayout.setVerticalGroup(
            pnlCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCHLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        rSPanelRound1.setAnchoBorde(1.0F);
        rSPanelRound1.setColorBackground(new java.awt.Color(239, 238, 244));
        rSPanelRound1.setColorBorde(new java.awt.Color(51, 153, 103));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INFORMACIÓN DEL PROPIETARIO");

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(239, 238, 244));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Dirección");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Teléfono:");

        lblNameOwnerDP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNameOwnerDP.setText("nombre");

        lblPhoneOwnerDP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhoneOwnerDP.setText("teléfono");

        lblAddressOwnerDP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAddressOwnerDP.setText("dirección");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneOwnerDP, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressOwnerDP, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameOwnerDP, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameOwnerDP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressOwnerDP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneOwnerDP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);

        jPanel7.setBackground(new java.awt.Color(239, 238, 244));

        btnNewPetPO.setBackground(new java.awt.Color(38, 166, 154));
        btnNewPetPO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/anadir (1).png"))); // NOI18N
        btnNewPetPO.setText("Mascota");
        btnNewPetPO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNewPetPO.setHideActionText(true);
        btnNewPetPO.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNewPetPO.setIconTextGap(8);
        btnNewPetPO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewPetPOMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNewPetPOMousePressed(evt);
            }
        });
        btnNewPetPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPetPOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewPetPO, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btnNewPetPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7);

        javax.swing.GroupLayout rSPanelRound1Layout = new javax.swing.GroupLayout(rSPanelRound1);
        rSPanelRound1.setLayout(rSPanelRound1Layout);
        rSPanelRound1Layout.setHorizontalGroup(
            rSPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelRound1Layout.createSequentialGroup()
                .addGroup(rSPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rSPanelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rSPanelRound1Layout.setVerticalGroup(
            rSPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelRound1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(239, 238, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 103)));

        rSTableMetro1.setBackground(new java.awt.Color(240, 240, 240));
        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"C180", "mascota", "canina", "mestiza", "2019/10/12", "MACHO", "negro"},
                {"C181", "mascota", "canina", "mestiza", "2020/01/03", "HEMBRA", "negro"}
            },
            new String [] {
                "# DE HISTORIA", "NOMBRE", "ESPECIE", "RAZA", "EDAD", "SEXO", "COLOR"
            }
        ));
        rSTableMetro1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        rSTableMetro1.setBackgoundHead(new java.awt.Color(51, 153, 103));
        rSTableMetro1.setBackgoundHover(new java.awt.Color(204, 204, 204));
        rSTableMetro1.setColorBorderHead(new java.awt.Color(51, 153, 103));
        rSTableMetro1.setColorBorderRows(new java.awt.Color(51, 153, 103));
        rSTableMetro1.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        rSTableMetro1.setColorSecondary(new java.awt.Color(239, 238, 244));
        rSTableMetro1.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        rSTableMetro1.setEffectHover(true);
        rSTableMetro1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rSTableMetro1.setFontHead(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSTableMetro1.setFontRowHover(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rSTableMetro1.setFontRowSelect(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rSTableMetro1.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSTableMetro1.setGridColor(new java.awt.Color(51, 153, 103));
        rSTableMetro1.setRowHeight(40);
        rSTableMetro1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        rSTableMetro1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        rSTableMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rSTableMetro1);
        if (rSTableMetro1.getColumnModel().getColumnCount() > 0) {
            rSTableMetro1.getColumnModel().getColumn(0).setResizable(false);
            rSTableMetro1.getColumnModel().getColumn(1).setResizable(false);
            rSTableMetro1.getColumnModel().getColumn(2).setResizable(false);
            rSTableMetro1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            this.dispose();
            if (switchHC) {
                formHC.close(evt);
                switchHC = false;
            }

        }
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_btnMinMouseClicked

    private void pnlCHMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCHMouseDragged
        this.setLocation(evt.getXOnScreen() - layoutX, evt.getYOnScreen() - layoutY);
    }//GEN-LAST:event_pnlCHMouseDragged

    private void pnlCHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCHMousePressed
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            layoutX = evt.getX();
            layoutY = evt.getY();
        }
    }//GEN-LAST:event_pnlCHMousePressed

    private void btnNewPetPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPetPOActionPerformed

    }//GEN-LAST:event_btnNewPetPOActionPerformed

    private void rSTableMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro1MouseClicked
        openClinicHistory();
    }//GEN-LAST:event_rSTableMetro1MouseClicked

    private void btnNewPetPOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewPetPOMousePressed

    }//GEN-LAST:event_btnNewPetPOMousePressed

    private void btnNewPetPOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewPetPOMouseClicked
        //abrir formulario
        openFrmPets(evt);
        //llenar camps
       insertDetailOwner();
    }//GEN-LAST:event_btnNewPetPOMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPetOfOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPetOfOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPetOfOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPetOfOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPetOfOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnClose;
    private rojeru_san.RSButton btnMin;
    private rojeru_san.RSButton btnNewPetPO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddressOwnerDP;
    private javax.swing.JLabel lblNameOwnerDP;
    private javax.swing.JLabel lblPhoneOwnerDP;
    private javax.swing.JPanel pnlCH;
    private rojeru_san.rspanel.RSPanelRound rSPanelRound1;
    private RSMaterialComponent.RSTableMetro rSTableMetro1;
    // End of variables declaration//GEN-END:variables
}
